<a href="https://colab.research.google.com/github/meghana1209/genai_ml_workshop/blob/main/workshop2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

workshop day 2
hoilday_package_prediction

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [12]:
df = pd.read_csv("Travel.csv")

In [4]:
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [6]:
df.shape

(4888, 20)

In [7]:
df.describe()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [9]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [10]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

data cleaning converting this numerical data

#checking for the null values

In [18]:
df.isnull()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4884,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4885,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4886,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

mode -frequent numbers
median - middle value

In [20]:
len(df)

4888

In [21]:
df.isnull().sum()/len(df)*100

CustomerID                  0.000000
ProdTaken                   0.000000
Age                         4.623568
TypeofContact               0.511457
CityTier                    0.000000
DurationOfPitch             5.135025
Occupation                  0.000000
Gender                      0.000000
NumberOfPersonVisiting      0.000000
NumberOfFollowups           0.920622
ProductPitched              0.000000
PreferredPropertyStar       0.531915
MaritalStatus               0.000000
NumberOfTrips               2.864157
Passport                    0.000000
PitchSatisfactionScore      0.000000
OwnCar                      0.000000
NumberOfChildrenVisiting    1.350245
Designation                 0.000000
MonthlyIncome               4.766776
dtype: float64

# #counting the proportion of customer by gender

In [23]:
df["Gender"].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [24]:
df["Gender"]=df["Gender"].replace("Fe Male","Female")

In [25]:
df["Gender"].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [26]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [29]:
df["MaritalStatus"]=df["MaritalStatus"].replace("Unmarried","Single")

In [30]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married     2340
Single      1598
Divorced     950
Name: count, dtype: int64

In [31]:
df["TypeofContact"].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [32]:
df["NumberOfTrips"].value_counts()

NumberOfTrips
2.0     1464
3.0     1079
1.0      620
4.0      478
5.0      458
6.0      322
7.0      218
8.0      105
19.0       1
21.0       1
20.0       1
22.0       1
Name: count, dtype: int64

In [33]:
	df["NumberOfChildrenVisiting"].value_counts()

NumberOfChildrenVisiting
1.0    2080
2.0    1335
0.0    1082
3.0     325
Name: count, dtype: int64

In [34]:
	df["Designation"].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [35]:
df.describe()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [36]:
df.describe(exclude="object") # getting a no number data include=object if want

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [37]:
df.info() # object means catorigical data or test data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
 20  MaritalStatus	            4888 non-null   object
dtypes: float64(7), int64(7), object(7)
memory usage: 802.1+ KB

In [38]:
### impute the missing valuses in the age column by the median value
df["Age"].median()

36.0

In [43]:
## using 36 to replace the null values in the age column
df["Age"].fillna(df["Age"].median(),inplace=True)

In [44]:
df["Age"].isnull().sum()

0

In [45]:
#impute the missing values duration of pitch with the median values  ----coulnm name DurationOfPitch
df["DurationOfPitch"].median()

13.0

In [48]:
### using 13 to replace it by median 13
df["DurationOfPitch"].fillna(df["DurationOfPitch"].median(),inplace=True)

In [49]:
df["DurationOfPitch"].isnull().sum()

0

In [51]:
## impution the missing values for the noof trips ----column name  NumberOfTrips
df["NumberOfTrips"].isnull().sum()

140

In [52]:
df["NumberOfTrips"].median()

3.0

In [54]:
df["NumberOfTrips"].fillna(df["NumberOfTrips"].median(),inplace=True)

In [55]:
df["NumberOfTrips"].isnull().sum()

0

In [ ]:
#impute the mode for the TypeofContact , NumberOfFollowups  ,PreferredPropertyStar ,NumberOfChildrenVisiting the are numberical but discrete

In [57]:
df["TypeofContact"].isnull().sum()

25

In [58]:
df["NumberOfFollowups"].isnull().sum()

45

In [59]:
df["PreferredPropertyStar"].isnull().sum()

26

In [60]:
df["NumberOfChildrenVisiting"].isnull().sum()

66

In [61]:
df["TypeofContact"].mode()

0    Self Enquiry
Name: TypeofContact, dtype: object

In [74]:
df["TypeofContact"].mode()[0] # to acces only the value

'Self Enquiry'

In [62]:
df["TypeofContact"].fillna(df["TypeofContact"].mode()[0],inplace=True)

In [63]:
df["TypeofContact"].isnull().sum()

0

In [73]:
df["NumberOfFollowups"].mode()

0    4.0
Name: NumberOfFollowups, dtype: float64

In [65]:
df["NumberOfFollowups"].fillna(df["NumberOfFollowups"].mode()[0],inplace=True)

In [66]:
df["NumberOfFollowups"].isnull().sum()

0

In [67]:
df["PreferredPropertyStar"].mode()[0]

3.0

In [68]:
df["PreferredPropertyStar"].fillna(df["PreferredPropertyStar"].mode()[0],inplace=True)

In [69]:
df["PreferredPropertyStar"].isnull().sum()

0

In [75]:
df["NumberOfChildrenVisiting"].mode()

0    1.0
Name: NumberOfChildrenVisiting, dtype: float64

In [71]:
df["NumberOfChildrenVisiting"].fillna(df["NumberOfChildrenVisiting"].mode()[0],inplace=True)

In [72]:
df["NumberOfChildrenVisiting"].isnull().sum()

0

In [77]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                           0
TypeofContact                 0
CityTier                      0
DurationOfPitch               0
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups             0
ProductPitched                0
PreferredPropertyStar         0
MaritalStatus                 0
NumberOfTrips                 0
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting      0
Designation                   0
MonthlyIncome               233
MaritalStatus\t               0
dtype: int64

In [78]:
df["MonthlyIncome"].fillna(df["MonthlyIncome"].median(),inplace=True)

In [79]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
MaritalStatus\t             0
dtype: int64

Feature Engineering

In [ ]:
# feature engineering --- gives a beeter outcome of the output variable ; like heart predictions ---- ht,wt--->bmi--->heart diesses yes or no
#dimension analysis

In [82]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome',
       'MaritalStatus\t'],
      dtype='object')

In [83]:
#creating a total visiting
df["TotalVisiting"]=df["NumberOfPersonVisiting"]+df["NumberOfChildrenVisiting"]

In [84]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome',
       'MaritalStatus\t', 'TotalVisiting'],
      dtype='object')

In [86]:
df.drop(['NumberOfPersonVisiting','NumberOfChildrenVisiting'],axis="columns",inplace=True)

In [87]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfFollowups',
       'ProductPitched', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'Designation', 'MonthlyIncome', 'MaritalStatus\t', 'TotalVisiting'],
      dtype='object')

In [88]:
df.drop(['CustomerID'],axis="columns",inplace=True)

In [89]:
df.columns

Index(['ProdTaken', 'Age', 'TypeofContact', 'CityTier', 'DurationOfPitch',
       'Occupation', 'Gender', 'NumberOfFollowups', 'ProductPitched',
       'PreferredPropertyStar', 'MaritalStatus', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'Designation', 'MonthlyIncome',
       'MaritalStatus\t', 'TotalVisiting'],
      dtype='object')

In [91]:
df.shape

(4888, 19)

In [ ]:
## train test and split, seprate the data

In [92]:
X=df.drop(["ProdTaken"],axis="columns")

In [93]:
y=df["ProdTaken"]

In [94]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [95]:
from sklearn.model_selection import train_test_split

In [96]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=28)

In [98]:
X_train.shape

(3910, 18)

In [99]:
X_test.shape

(978, 18)

In [ ]:
## one hot encoding  ---- to make categorie=cal data to  binary
## min max scaling -numberical colunms to scale the data

In [104]:
 # create a column tranformation
 cat_features=X.select_dtypes(include="object").columns
cat_features

Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation', 'MaritalStatus\t'],
      dtype='object')

In [109]:
num_features=X.select_dtypes(exclude="object").columns
num_features

Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object')

In [110]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

## sets up a preprocesing pipelines using columnTranfromer from scikit
## cate and numerical features

In [111]:
numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first') #as.type(float)

In [114]:
#creating preprocessing pipelines

preprocessor=ColumnTransformer([("OneHotEncoder",oh_transformer,cat_features),
                             ("StandardScaler",numeric_transformer,num_features)])

In [116]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation', 'MaritalStatus\t'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object'))])

In [117]:
X_train=preprocessor.fit_transform(X_train)

In [118]:
X_train

array([[ 1.        ,  0.        ,  0.        , ...,  0.7804188 ,
         2.07726895,  0.63516633],
       [ 1.        ,  0.        ,  0.        , ...,  0.7804188 ,
         0.3650724 , -1.47008968],
       [ 1.        ,  0.        ,  1.        , ...,  0.7804188 ,
        -0.00964618,  0.63516633],
       ...,
       [ 1.        ,  0.        ,  1.        , ...,  0.7804188 ,
        -1.12624556, -0.76833768],
       [ 1.        ,  0.        ,  1.        , ...,  0.7804188 ,
        -0.1125291 ,  1.33691833],
       [ 1.        ,  0.        ,  1.        , ..., -1.28136329,
        -0.52367328, -1.47008968]])

In [119]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,-0.714400,-0.886206,-0.713905,-0.725409,-0.129728,1.581280,-1.519047,0.780419,2.077269,0.635166
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.466164,-0.648482,1.293552,-0.725409,-0.676907,-0.632399,-1.519047,0.780419,0.365072,-1.470090
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,-0.714400,0.896724,1.293552,0.530725,-0.676907,1.581280,-1.519047,0.780419,-0.009646,0.635166
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.714400,1.728758,-1.717634,-0.725409,-0.129728,1.581280,0.680758,-1.281363,-0.409359,-0.066586
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.714400,2.323069,-0.713905,-0.725409,-1.224086,-0.632399,-0.052510,0.780419,-0.226456,0.635166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,-0.714400,-0.767344,-1.717634,-0.725409,-0.676907,-0.632399,-0.052510,-1.281363,0.042086,0.635166
3906,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714400,-0.054172,-0.713905,-0.725409,0.417452,-0.632399,-0.052510,0.780419,-1.247923,-0.768338
3907,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.714400,-0.886206,-0.713905,0.530725,-1.224086,-0.632399,0.680758,0.780419,-1.126246,-0.768338
3908,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.714400,-0.054172,0.289823,1.786859,1.511810,1.581280,0.680758,0.780419,-0.112529,1.336918
3909,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.466164,2.085345,-0.713905,-0.725409,-0.676907,1.581280,1.414027,-1.281363,-0.523673,-1.470090

In [120]:
pd.DataFrame(X_train).head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,-0.714400,-0.886206,-0.713905,-0.725409,-0.129728,1.581280,-1.519047,0.780419,2.077269,0.635166
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.466164,-0.648482,1.293552,-0.725409,-0.676907,-0.632399,-1.519047,0.780419,0.365072,-1.470090
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,-0.714400,0.896724,1.293552,0.530725,-0.676907,1.581280,-1.519047,0.780419,-0.009646,0.635166
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.714400,1.728758,-1.717634,-0.725409,-0.129728,1.581280,0.680758,-1.281363,-0.409359,-0.066586
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.714400,2.323069,-0.713905,-0.725409,-1.224086,-0.632399,-0.052510,0.780419,-0.226456,0.635166

In [122]:
X_test=preprocessor.transform(X_test)

In [126]:
from sklearn.tree import DecisionTreeClassifier #descision tree model creation and training
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,precision_score,recall_score

In [127]:
dt=DecisionTreeClassifier()
lr=LogisticRegression()

In [130]:
###train your models
dt.fit(X_train,y_train)
lr.fit(X_train,y_train)

LogisticRegression()

In [135]:
dt.score(X_train,y_train)

1.0

In [136]:
dt.score(X_test,y_test)

0.9069529652351738

In [137]:
lr.score(X_train,y_train)

0.851150895140665

In [138]:
lr.score(X_test,y_test)

0.8231083844580777

In [139]:
y_train_pred= dt.predict(X_train)

In [142]:
y_test_pred=dt.predict(X_test)

In [146]:
acc_train=accuracy_score(y_train,y_train_pred)
acc_train

1.0

In [150]:
acc_test=accuracy_score(y_test,y_test_pred)
acc_test

0.9069529652351738

In [153]:
 pre_train=precision_score(y_train,y_train_pred)
pre_train

1.0

In [155]:
pre_train=precision_score(y_test,y_test_pred)
pre_train

0.7708333333333334

In [156]:
re_train=recall_score(y_train,y_train_pred)
re_train

1.0

In [158]:
re_test=recall_score(y_test,y_test_pred)
re_test

0.7589743589743589